{
 "title": "Energy",
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "SHOW TAG VALUES FROM \"electricity\" WITH KEY = \"site\""
   }
  ]
 },
 "panels": [
  {
   "title": "Energy by Hour",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "SELECT sum(\"consumption\") FROM \"electricity\" WHERE $timeFilter AND \"site\" =~ /^$site$/ GROUP BY time(1h), \"timeofuse\"::tag",
     "alias": "$tag_timeofuse"
    },
    {
     "query": "SELECT sum(\"export\") FROM \"electricity\" WHERE $timeFilter AND \"site\" =~ /^$site$/ GROUP BY time(1h)",
     "alias": "Solar export"
    }
   ]
  },
  {
   "title": "Cost by Hour",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyAUD" } },
   "targets": [
    {
     "query": "SELECT sum(\"cost\") FROM \"electricity\" WHERE $timeFilter AND \"site\" =~ /^$site$/ GROUP BY time(1h), \"timeofuse\"::tag",
     "alias": "$tag_timeofuse"
    },
    {
     "query": "SELECT sum(\"credit\") FROM \"electricity\" WHERE $timeFilter AND \"site\" =~ /^$site$/ GROUP BY time(1h)",
     "alias": "Feed-in credit"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"consumption\") FROM \"electricity\" WHERE $timeFilter AND \"site\" =~ /^$site$/"
    }
   ]
  },
  {
   "title": "By Time of Use",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"consumption\") FROM \"electricity\" WHERE $timeFilter AND \"site\" =~ /^$site$/ GROUP BY \"timeofuse\"::tag",
     "alias": "$tag_timeofuse"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyAUD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"cost\") FROM \"electricity\" WHERE $timeFilter AND \"site\" =~ /^$site$/",
     "alias": "Usage"
    },
    {
     "query": "SELECT sum(\"credit\") FROM \"electricity\" WHERE $timeFilter AND \"site\" =~ /^$site$/",
     "alias": "Feed-in"
    },
    {
     "query": "SELECT sum(\"cost\") - sum(\"credit\") FROM \"daily\" WHERE $timeFilter AND \"site\" =~ /^$site$/",
     "alias": "Net"
    }
   ]
  },
  {
   "title": "Current Rates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyAUD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"unitprice\") FROM \"rate\" WHERE time <= now() AND \"site\" =~ /^$site$/ GROUP BY \"timeofuse\"::tag",
     "alias": "$tag_timeofuse"
    },
    {
     "query": "SELECT last(\"dailycharge\") FROM \"supply\" WHERE time <= now() AND \"site\" =~ /^$site$/",
     "alias": "Supply /day"
    }
   ]
  }
 ]
}